app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

class User(UserMixin,db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer,primary_key = True)
	username = db .Column(db.String(255))
	email = db.Column(db.String(255), unique = True, index = True)
	password_hash = db.Column(db.String(255))

	@property
	def password(self, password):
		raise AttributeError('You Cannot Read the password attribute')

	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self,password):
		return check_password_hash(self.password_hash,password)

	def __repr__(self):
		return f'User {self.username}'



class Pitch(db.Model):
    __tablename_='pitches'
    id = db.Column(db.Integer,primary_key = True)
    category = db.Column(db.String(255))
    title = db.Column(db.String(255))
    body = db.Column(db.String())
    
    def save_pitches(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls):
        pitches = Pitch.query.all() 
        return pitches

    @classmethod
    def get_categories(cls, category):
        pitch_cat = Pitch.query.filter_by(category=category)
        return pitch_cat

    def __init__(self,title, body, category):
        self.title= title
        self.body= body
        self.category= category



class Comment(db.Model):
    
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment= db.Column(db.String)
    pitches_id = db.Column(db.Integer,db.ForeignKey('pitch.id'))
    username =  db.Column(db.String)
    votes= db.Column(db.Integer)
    

    def save_comment(self):
        '''
        Function that saves comments
        '''
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_comments(cls):
        Comment.all_comments.clear()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SubmitField,BooleanField,RadioField,SelectField,FileField,PasswordField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Title',validators=[Required()])
    body =TextAreaField('Content',validators=[Required()])
    category =SelectField('Categories (Optional)', choices=[('pick_up','pick-up '), ('interview Pitch','interview Pitch'),
        ('product pitch', 'product pitch'), ('promotion pitch', 'promotion pitch')])
    submit = SubmitField('Submit')


class CommentsForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])
    author =TextAreaField('Author ',validators=[Required()])

    vote = RadioField('Vote',choices=[('upvote','upvote'),('downvote','downvote')],validators=[Required()])                                       
    submit = SubmitField('SUBMIT') 

app/__init__.py
from flask import Flask
from config import config_options 
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app=Flask(__name__)

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)


    #initializing flask extentions
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from . import main
from flask import render_template,request,redirect, url_for, abort
from flask_login import login_required,current_user
from ..models import Pitch,User,Comment
from .forms import PitchForm, CommentsForm

from .. import db


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to My Blog'


    # pitches = pitch.query.filter_by(category='glee').all()
    # print(pitches)
    pick_up = Pitch.query.filter_by(category = 'pick_up').all()
    interview = Pitch.query.filter_by(category = 'interview Pitch').all()
    product = Pitch.query.filter_by(category = 'product pitch').all()
    promotion = Pitch.query.filter_by(category = 'promotion pitch').all()
    comment = Comment.query.all()

    print(interview)

    return render_template('index.html',title=title,product = product,interview =interview,pick_up = pick_up, comment = comment)

@main.route('/newpitch' ,methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        pitches = Pitch(title = form.title.data,body = form.body.data,category = form.category.data)

        pitches.save_pitches()
        # print('Your Pitch has been succenssfully saved!')
        return redirect(url_for('main.index'))

    return render_template('newpitch.html', pitch_form = form)


@main.route('/pitch/comments/new',methods = ['GET','POST'])
@login_required
def new_comment():
    form = CommentsForm()          
    # vote_form = UpvoteForm()
    if form.validate_on_submit():
        new_comment = Comment(comment=form.comment.data,username=current_user.username)
        new_comment.save_comment()
        return redirect(url_for('main.index'))
    #title = f'{pitch_result.id} review'
    return render_template('new_comment.html',comment_form=form,vote_form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> </title>
        {% endif %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    </head>
    <body>
        <!-- Content block -->
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}
        {% block content %}

        {% endblock%}

        <!-- Navbar block  --> 

    </body>
</html

app/templates/create.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macro.html' as macro%}
{% block content %}
    <div class="container">
        {{wtf.quick_form(pitch_form)}}
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} 
{% import 'macro.html' as macro %}
{% block content %}       

      <p><a href="{{url_for('main.new_pitch')}}">Create a Pitch </a></p>

      {{macro.displayPitchList(pick_up)}}

      {{macro.displayPitchList(product)}}

      {{macro.displayPitchList(promotion)}}

      {{macro.displayPitchList(interview)}}


      <div class="col-md-4">
      	<h1>Comments</h1>
     
     <div class="well" style="background-color: black; color: white; border-top-right-radius: 30px;border-bottom-left-radius: 30px; border-right: 20px solid #03A9F4">
      <li>	
      {{macro.displayCommentList(comment)}}

       </li>               
                         
                    </div>

                    </div>
                </div>
            </div>
{% endblock %}

app/templates/login.html
{% extends 'auth/auth-base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content%}

<div class="container">
  <div class="row">

    <div class="col-md-2"> </div>

    <div class="col-md-8">
      <!-- Flash message -->
      {% for message in get_flashed_messages() %}
          <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
          </div>

      {% endfor %}
      <!-- Login form  -->

      {{ wtf.quick_form(login_form) }}

      <p> Don't  have an account?  <a href="{{url_for('auth.register')}}" >Create an Account</a></p>

    </div>

    <div class="col-md-2"> </div>

  </div>
</div>


{%endblock%}

app/templates/macro.html
{% macro displayPitchList(pitch_list) %}
    {% for pitch in pitch_list %}
    
  <div class="col-md-4">
    <h1>Blog</h1>
    <div class="card border-success mb-3">
                <div class="panel panel-info" style="height:auto;width:auto;margin-bottom:20%;margin-left:0%;">
                    <div class="panel-heading" style="background-color: black;height: 70px; border-top-left-radius: 30px">
                        <h2>{{pitch.title}}</h2>
                    </div>
                    <div class="panel-heading">
                        <h2>{{pitch.body}}</h2>
                    </div>
                    <div class="panel-heading" style="background-color: black; height: 70px; border-bottom-right-radius: 30px";>
                        <h2>{{pitch.category}}</h2>
                    
                    </div>

                    </div>
                </div>
            </div>
            
    {% endfor %}
{% endmacro %}

{% macro displayCommentList(comment_list) %} {% for comment in comment_list %}
<div class="card-header bg-transparent border-success">{{comment.comment}}</div>
{% endfor %} {% endmacro %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
        <div class="col-md-3 col-lg-3 col-xl-3">    
        </div>

        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 ">
        	
                {{ wtf.quick_form(comment_form) }}

                
        </div>
        <div class="col-md-3 col-lg-3 col-xl-3">  
        </div>

</div>

{% endblock %}

app/templates/newpitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(pitch_form)}}
s
</div>
{% endblock  %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}

app/templates/register.html
{% extends 'auth/auth-base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="col-md-4"> </div>
<div class="col-md-8">
	<input type='text' placeholder='Username' />
  {{wtf.quick_form(registration_form)}}

 </div>



{% endblock%}